<?php

namespace Tests\Feature;

use App\Models\Post;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Symfony\Component\HttpFoundation\Response;
use Tests\TestCase;

class CRUDPostExampleTest extends TestCase
{

    use RefreshDatabase;
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
    }

    /** @test */
    public function CreatePost()
    {
        $postData = Post::factory()->make()->toArray();
//         $postData = [
//            'title' => $this->faker->sentence(),
//            'body' => $this->faker->paragraph(),
//        ];
        $response = $this->post('/posts', $postData);
        $response->assertStatus(Response::HTTP_CREATED);
        $this->assertDatabaseHas('posts', $postData);
    }

    /** @test */
    public function ReadPost()
    {
        $post = Post::factory()->create();

        $response = $this->get('/posts/' . $post->id);

        $response->assertStatus(Response::HTTP_OK);

        $response->assertJsonFragment([
            'title' => $post->title,
            'body' => $post->body,
        ]);
    }

    /** @test */
    public function UpdateTest()
    {
        $post = Post::factory()->create();

        $updateData = [
            'title' => $this->faker->sentence(),
            'body' => $this->faker->paragraph(),
        ];
        $response = $this->put('/posts/' . $post->id, $updateData);

        $response->assertStatus(Response::HTTP_OK);
        $this->assertDatabaseHas('posts', $updateData);
    }

    /** @test */
    public function can_list_posts()
    {
        $posts = Post::factory()->count(5)->create();
        $response = $this->get('posts');
        $response->assertStatus(Response::HTTP_OK);
        $this->assertCount(5, $posts);

    }
}
