<?php

namespace Tests\Feature;

use App\Models\Post;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Symfony\Component\HttpFoundation\Response;
use Tests\TestCase;

class CRUDPostExampleTest extends TestCase
{

    use RefreshDatabase;
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
    }

    /** @test */
    public function CreatePost()
    {
         $postData = [
            'title' => $this->faker->sentence(),
            'body' => $this->faker->paragraph(),
        ];
        $response = $this->post('/posts', $postData);
        $response->assertStatus(Response::HTTP_CREATED);
        $this->assertDatabaseHas('posts', $postData);
    }

    /** @test */
    public function ShowPost()
    {
        $post = Post::factory()->create();

        $response = $this->get('/posts/'.$post->id);

        $response->assertStatus(Response::HTTP_OK);

        $response->assertJson([
            'title' => $post->title,
            'body' => $post->body,
        ]);
    }

    /** @test */
    public function UpdateTest()
    {
        $post = Post::factory()->create();

        $updateData = [
            'title' => $this->faker->sentence(),
            'body' => $this->faker->paragraph(),
        ];
        $response = $this->put('/posts/'.$post->id, $updateData );

        $response->assertStatus(Response::HTTP_OK);
        $this->assertDatabaseHas('posts', $updateData);
    }
}
