<?php

namespace Tests\Feature;

use App\Models\Product;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Symfony\Component\HttpFoundation\Response;
use Tests\TestCase;

class CRUDProductExampleText extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    /** @test */
    public function ProductCreate()
    {
        $this->withoutExceptionHandling();
        $productData = Product::factory()->make()->toArray();
        $data = [
            'name' => $this->faker->name(),
            'description' => $this->faker->sentence(),
            'price' => $this->faker->numberBetween(20, 500),
        ];
        $response = $this->post(route('product.store'), $productData);
        $response->assertStatus(201);
        $response->assertRedirect(route('product.index'));
        $this->assertDatabaseHas('products', $data);
    }

    /** @test */
    public function it_should_display_list_of_products()
    {
        // Arrange
        $products = Product::factory()->count(3)->create();

        // Act
        $response = $this->get(route('product.index'));

        // Assert
        $response->assertSuccessful();
        $response->assertViewIs('products.index');

    }
}
